### ISSUE TITLE
Glitch in the "minimize to tray" setting (minor)

### ISSUE THREAD

**Issue by xNul** [vertcoin/One-Click-Miner#15] opened 2017-10-24 22:57 UTC
This glitch causes OCM to appear both in your tray and on the bottom of your desktop like so:
![glitch](https://i.imgur.com/HeBgyKQ.png)

To reproduce, try turning on the setting, minimizing to the tray, opening OCM from the tray, and minimizing it again.  It should now be at the bottom of your desktop, similar to the above image.

**Comment by zemrys** [comment] 2017-10-25 13:26
I am not able to recreate this issue.

**Comment by patchandthat** [comment] 2017-10-25 13:52
Could not reproduce this either.  However, after turning on the minimise to tray setting, minimising and restoring, I had no OCM icon on the Taskbar. Needed to restart OCM to get it back.

**Comment by zemrys** [comment] 2017-10-25 20:26
I am not able to recreate your issue either patch.

**Comment by xNul** [comment] 2017-10-25 20:49
I can't reproduce patch's bug either.

**Comment by patchandthat** [comment] 2017-10-26 09:36
Ok, I'll raise it as a separate issue if I can come up with reliable repro steps

**Comment by xNul** [comment] 2017-11-22 06:09
Just updated OCM to 1.1.6 and I don't have this issue anymore.  Don't know if the bug has been purged, or I just got lucky.

**Comment by xNul** [comment] 2017-11-22 06:37
Okay, never mind, it's back.

**Comment by zemrys** [comment] 2018-01-04 14:42
Closing due to lack of recreation/reports.

**Closed as completed** 2018-01-04 14:42 UTC
