### ISSUE TITLE
Parameter cannot be null

### ISSUE THREAD

**Issue by ghost** [vertcoin/One-Click-Miner#11] opened 2017-10-21 09:27 UTC
The miner throws a window stating that Value cannot be null. Parameter name: s. this window blocks all other activity on the miner, preventing users from updating fields or populating the parameters. Closing the window causes another window to spawn with the same error message.

Also, windows is detecting a virus with this one. strongly.

**Comment by foxdundee** [comment] 2017-10-21 10:45
Ive experienced the same since morning. Had to End Task and restart, yet again the issue persists. 
This after i ticked 1 option in Settings - like "check peridocially to keep miner" "auto start with windows".  
Happens both with CPU and Nvidia option

**Comment by BobbyGR** [comment] 2017-10-21 11:54
Can you go over how you can make this error occur?

**Comment by ghost** [comment] 2017-10-21 14:15
I started the miner and error appears at startup I'm on windows 10.

**Comment by patchandthat** [comment] 2017-10-23 11:57
@Shaithias @foxdundee  can you post the logs after the error happens?

After pressing OK on the message box, go the the View menu > System log.

**Comment by foxdundee** [comment] 2017-10-23 13:40
Hi @Patrick
There were several errors notif boxes opening rapidly so had to End Task. I
proceeded to uninstall prog and reinstall thinking i may have made a
mistake. If the error occurs again, will post the logs as directed.

On 23 Oct 2017 19:57, "Patrick Allwood" <notifications@github.com> wrote:

@Shaithias <https://github.com/shaithias> @foxdundee
<https://github.com/foxdundee> can you post the logs after the error
happens?

After pressing OK on the message box, go the the View menu > System log.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/vertcoin/One-Click-Miner/issues/11#issuecomment-338635618>,
or mute the thread

**Comment by ghost** [comment] 2017-10-23 15:33
We can't get past the message box. It spawns new boxes as soon as the old one is clicked.

Sent from my Cyanogen phone

On Oct 23, 2017 6:57 AM, Patrick Allwood <notifications@github.com> wrote:

@Shaithias<https://github.com/shaithias> @foxdundee<https://github.com/foxdundee> can you post the logs after the error happens?

After pressing OK on the message box, go the the View menu > System log.

**Comment by zemrys** [comment] 2017-10-23 17:09
If you could, navigate to the My Documents\Vertcoin One-Click Miner directory and post the text contained within the settings.json file (be sure to remove any private info).  This may give me more of a clue.

Until the issue is sorted, turn off the OCM and try deleting the settings.json then relaunch the OCM.

**Comment by patchandthat** [comment] 2017-10-26 10:47
The logging code should be logging a full stacktrace on exceptions, so the log will say exactly which line is causing this.

The log file itself is `My Documents\Vertcoin One-Click Miner\syslog.txt`

I believe whats happening is there is the keep-miner-alive check trying to restart the miner, and there is something going bang when trying to write the updated miner config file, and this happens on a loop continually. 

Specifically the line, `Dim jsonFormatted As String = JValue.Parse(jsonstring).ToString(Formatting.Indented)` I think `jsonstring` is null, and the Parse code internally tries to create a StringReader, which takes a single argument `s`, which would blow up with the exact message we're seeing.

I'd suggest changing when writing the miner config happens, so that it's only called when starting the first time, or when settings actually change, and not called in the keep-alive loop.

**Comment by zemrys** [comment] 2017-10-26 12:41
I looked into what you mentioned.  I made some changes that might take care of it [b68d4e7](https://github.com/vertcoin/One-Click-Miner/commit/b68d4e7757f9d7c7aa50ed8b2198afea07c3f113)

**Comment by zemrys** [comment] 2017-10-27 14:18
Closing for now, patch introduced in [b68d4e7](https://github.com/vertcoin/One-Click-Miner/commit/b68d4e7757f9d7c7aa50ed8b2198afea07c3f113).

**Closed as completed by zemrys** 2017-10-27 14:18 UTC
